// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using backend.Models;

#nullable disable

namespace backend.Migrations
{
    [DbContext(typeof(BackendDbContext))]
    partial class BackendDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DetalleOrdenBebida", b =>
                {
                    b.Property<int>("Id_Bebida")
                        .HasColumnType("int");

                    b.Property<int>("Id_Detalle_Orden")
                        .HasColumnType("int");

                    b.HasKey("Id_Bebida", "Id_Detalle_Orden");

                    b.HasIndex("Id_Detalle_Orden");

                    b.ToTable("DetalleOrdenBebida");
                });

            modelBuilder.Entity("DetalleOrdenPlatillo", b =>
                {
                    b.Property<int>("Id_Detalle_Orden")
                        .HasColumnType("int");

                    b.Property<int>("Id_Platillo")
                        .HasColumnType("int");

                    b.HasKey("Id_Detalle_Orden", "Id_Platillo");

                    b.HasIndex("Id_Platillo");

                    b.ToTable("DetalleOrdenPlatillo");
                });

            modelBuilder.Entity("backend.Models.Administrador", b =>
                {
                    b.Property<int>("Id_Administrador")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id_Administrador"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("Contrasena")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Correo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id_Administrador");

                    b.ToTable("Administrador");

                    b.HasData(
                        new
                        {
                            Id_Administrador = 1,
                            Activo = true,
                            Contrasena = "root",
                            Correo = "admin@gmail.com",
                            Nombre = "admin"
                        });
                });

            modelBuilder.Entity("backend.Models.Bebida", b =>
                {
                    b.Property<int>("Id_Bebida")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id_Bebida"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int?>("Id_Categoria")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Precio")
                        .HasPrecision(7, 2)
                        .HasColumnType("int");

                    b.HasKey("Id_Bebida");

                    b.HasIndex("Id_Categoria");

                    b.ToTable("Bebida");

                    b.HasData(
                        new
                        {
                            Id_Bebida = 1,
                            Descripcion = "Jugo natural exprimido de naranjas frescas.",
                            Id_Categoria = 4,
                            Nombre = "Jugo de Naranja",
                            Precio = 4000
                        },
                        new
                        {
                            Id_Bebida = 2,
                            Descripcion = "Té verde helado naturalmente antioxidante y revitalizante.",
                            Id_Categoria = 4,
                            Nombre = "Té Verde Helado",
                            Precio = 3500
                        },
                        new
                        {
                            Id_Bebida = 3,
                            Descripcion = "Bebida refrescante y nutritiva con mezcla de frutas frescas y yogurt.",
                            Id_Categoria = 4,
                            Nombre = "Smoothie de Frutas",
                            Precio = 4500
                        },
                        new
                        {
                            Id_Bebida = 4,
                            Descripcion = "Agua de coco natural, refrescante y bajo en calorías.",
                            Id_Categoria = 4,
                            Nombre = "Agua de Coco",
                            Precio = 3000
                        },
                        new
                        {
                            Id_Bebida = 5,
                            Descripcion = "Limonada refrescante preparada con limones frescos.",
                            Id_Categoria = 4,
                            Nombre = "Limonada Natural",
                            Precio = 3500
                        },
                        new
                        {
                            Id_Bebida = 6,
                            Descripcion = "Cóctel refrescante sin alcohol con menta, lima, azúcar, soda y hierbabuena.",
                            Id_Categoria = 4,
                            Nombre = "Mojito sin Alcohol",
                            Precio = 3800
                        },
                        new
                        {
                            Id_Bebida = 7,
                            Descripcion = "Café frío mezclado con hielo, ideal para días calurosos.",
                            Id_Categoria = 5,
                            Nombre = "Café Frappé",
                            Precio = 4000
                        },
                        new
                        {
                            Id_Bebida = 8,
                            Descripcion = "Cóctel frozen con ron, crema de coco y jugo de piña.",
                            Id_Categoria = 4,
                            Nombre = "Piña Colada Frozen",
                            Precio = 6500
                        },
                        new
                        {
                            Id_Bebida = 9,
                            Descripcion = "Cóctel frozen de tequila, triple sec, jugo de lima y azúcar.",
                            Id_Categoria = 4,
                            Nombre = "Margarita Frozen",
                            Precio = 7000
                        },
                        new
                        {
                            Id_Bebida = 10,
                            Descripcion = "Cóctel frozen con ron blanco, fresas frescas, jugo de limón y azúcar.",
                            Id_Categoria = 4,
                            Nombre = "Daiquiri de Fresa Frozen",
                            Precio = 6800
                        });
                });

            modelBuilder.Entity("backend.Models.Categoria", b =>
                {
                    b.Property<int>("Id_Categoria")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id_Categoria"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id_Categoria");

                    b.ToTable("Categoria");

                    b.HasData(
                        new
                        {
                            Id_Categoria = 1,
                            Nombre = "Entradas"
                        },
                        new
                        {
                            Id_Categoria = 2,
                            Nombre = "Platos principales"
                        },
                        new
                        {
                            Id_Categoria = 3,
                            Nombre = "Postres"
                        },
                        new
                        {
                            Id_Categoria = 4,
                            Nombre = "Bebidas frías"
                        },
                        new
                        {
                            Id_Categoria = 5,
                            Nombre = "Bebidas calientes"
                        },
                        new
                        {
                            Id_Categoria = 6,
                            Nombre = "Ensaladas"
                        },
                        new
                        {
                            Id_Categoria = 7,
                            Nombre = "Sopas"
                        },
                        new
                        {
                            Id_Categoria = 8,
                            Nombre = "Aperitivos"
                        },
                        new
                        {
                            Id_Categoria = 9,
                            Nombre = "Sandwiches"
                        },
                        new
                        {
                            Id_Categoria = 10,
                            Nombre = "Mariscos"
                        });
                });

            modelBuilder.Entity("backend.Models.Chef", b =>
                {
                    b.Property<int>("Id_Chef")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id_Chef"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("Contrasena")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Correo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id_Chef");

                    b.ToTable("Chef");

                    b.HasData(
                        new
                        {
                            Id_Chef = 1,
                            Activo = true,
                            Contrasena = "root",
                            Correo = "ana.rodriguez@gmail.com",
                            Nombre = "Ana Rodríguez"
                        },
                        new
                        {
                            Id_Chef = 2,
                            Activo = true,
                            Contrasena = "root",
                            Correo = "pedro.gomez@gmail.com",
                            Nombre = "Pedro Gómez"
                        },
                        new
                        {
                            Id_Chef = 3,
                            Activo = true,
                            Contrasena = "root",
                            Correo = "lucia.fernandez@gmail.com",
                            Nombre = "Lucía Fernández"
                        },
                        new
                        {
                            Id_Chef = 4,
                            Activo = true,
                            Contrasena = "root",
                            Correo = "jorge.ramirez@gmail.com",
                            Nombre = "Jorge Ramírez"
                        },
                        new
                        {
                            Id_Chef = 5,
                            Activo = true,
                            Contrasena = "root",
                            Correo = "elena.sanchez@gmail.com",
                            Nombre = "Elena Sánchez"
                        });
                });

            modelBuilder.Entity("backend.Models.Cliente", b =>
                {
                    b.Property<int>("Id_Cliente")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id_Cliente"));

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.HasKey("Id_Cliente");

                    b.ToTable("Cliente");

                    b.HasData(
                        new
                        {
                            Id_Cliente = 1,
                            Apellido = "Martínez",
                            Nombre = "Ana"
                        },
                        new
                        {
                            Id_Cliente = 2,
                            Apellido = "Gómez",
                            Nombre = "Pedro"
                        },
                        new
                        {
                            Id_Cliente = 3,
                            Apellido = "López",
                            Nombre = "María"
                        },
                        new
                        {
                            Id_Cliente = 4,
                            Apellido = "Pérez",
                            Nombre = "Juan"
                        },
                        new
                        {
                            Id_Cliente = 5,
                            Apellido = "Sánchez",
                            Nombre = "Laura"
                        },
                        new
                        {
                            Id_Cliente = 6,
                            Apellido = "García",
                            Nombre = "Carlos"
                        },
                        new
                        {
                            Id_Cliente = 7,
                            Apellido = "Fernández",
                            Nombre = "Sofía"
                        },
                        new
                        {
                            Id_Cliente = 8,
                            Apellido = "Ramírez",
                            Nombre = "Diego"
                        },
                        new
                        {
                            Id_Cliente = 9,
                            Apellido = "Hernández",
                            Nombre = "Valentina"
                        },
                        new
                        {
                            Id_Cliente = 10,
                            Apellido = "Torres",
                            Nombre = "Luis"
                        },
                        new
                        {
                            Id_Cliente = 11,
                            Apellido = "Díaz",
                            Nombre = "Carmen"
                        },
                        new
                        {
                            Id_Cliente = 12,
                            Apellido = "Moreno",
                            Nombre = "Pablo"
                        },
                        new
                        {
                            Id_Cliente = 13,
                            Apellido = "Ortega",
                            Nombre = "Adriana"
                        },
                        new
                        {
                            Id_Cliente = 14,
                            Apellido = "Ruiz",
                            Nombre = "Martín"
                        },
                        new
                        {
                            Id_Cliente = 15,
                            Apellido = "González",
                            Nombre = "Julia"
                        },
                        new
                        {
                            Id_Cliente = 16,
                            Apellido = "Navarro",
                            Nombre = "Elena"
                        },
                        new
                        {
                            Id_Cliente = 17,
                            Apellido = "Jiménez",
                            Nombre = "Miguel"
                        },
                        new
                        {
                            Id_Cliente = 18,
                            Apellido = "Silva",
                            Nombre = "Sara"
                        },
                        new
                        {
                            Id_Cliente = 19,
                            Apellido = "López",
                            Nombre = "Andrés"
                        },
                        new
                        {
                            Id_Cliente = 20,
                            Apellido = "Martí",
                            Nombre = "Lucía"
                        });
                });

            modelBuilder.Entity("backend.Models.Cuenta", b =>
                {
                    b.Property<int>("Id_Cuenta")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id_Cuenta"));

                    b.Property<bool>("Cancelado")
                        .HasColumnType("bit");

                    b.Property<int>("Id_Cliente")
                        .HasColumnType("int");

                    b.Property<int>("Id_Orden")
                        .HasColumnType("int");

                    b.Property<decimal>("Total")
                        .HasColumnType("decimal(10, 2)");

                    b.HasKey("Id_Cuenta");

                    b.HasIndex("Id_Orden")
                        .IsUnique();

                    b.ToTable("Cuenta");

                    b.HasData(
                        new
                        {
                            Id_Cuenta = 1,
                            Cancelado = false,
                            Id_Cliente = 1,
                            Id_Orden = 1,
                            Total = 1500m
                        },
                        new
                        {
                            Id_Cuenta = 2,
                            Cancelado = true,
                            Id_Cliente = 2,
                            Id_Orden = 2,
                            Total = 1200m
                        },
                        new
                        {
                            Id_Cuenta = 3,
                            Cancelado = false,
                            Id_Cliente = 3,
                            Id_Orden = 3,
                            Total = 1800m
                        },
                        new
                        {
                            Id_Cuenta = 4,
                            Cancelado = false,
                            Id_Cliente = 4,
                            Id_Orden = 4,
                            Total = 900m
                        },
                        new
                        {
                            Id_Cuenta = 5,
                            Cancelado = true,
                            Id_Cliente = 5,
                            Id_Orden = 5,
                            Total = 2000m
                        },
                        new
                        {
                            Id_Cuenta = 6,
                            Cancelado = false,
                            Id_Cliente = 6,
                            Id_Orden = 6,
                            Total = 1600m
                        },
                        new
                        {
                            Id_Cuenta = 7,
                            Cancelado = false,
                            Id_Cliente = 7,
                            Id_Orden = 7,
                            Total = 2100m
                        },
                        new
                        {
                            Id_Cuenta = 8,
                            Cancelado = true,
                            Id_Cliente = 8,
                            Id_Orden = 8,
                            Total = 1400m
                        },
                        new
                        {
                            Id_Cuenta = 9,
                            Cancelado = false,
                            Id_Cliente = 9,
                            Id_Orden = 9,
                            Total = 1750m
                        },
                        new
                        {
                            Id_Cuenta = 10,
                            Cancelado = false,
                            Id_Cliente = 10,
                            Id_Orden = 10,
                            Total = 1950m
                        });
                });

            modelBuilder.Entity("backend.Models.DetalleOrden", b =>
                {
                    b.Property<int>("Id_Detalle_Orden")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id_Detalle_Orden"));

                    b.Property<int>("Cantidad_Bebida")
                        .HasColumnType("int");

                    b.Property<int>("Cantidad_Platillo")
                        .HasColumnType("int");

                    b.Property<int?>("Id_Bebida")
                        .HasColumnType("int");

                    b.Property<int>("Id_Orden")
                        .HasColumnType("int");

                    b.Property<int?>("Id_Platillo")
                        .HasColumnType("int");

                    b.Property<decimal>("Precio")
                        .HasPrecision(7, 2)
                        .HasColumnType("decimal(7,2)");

                    b.HasKey("Id_Detalle_Orden");

                    b.HasIndex("Id_Orden")
                        .IsUnique();

                    b.ToTable("DetalleOrden");

                    b.HasData(
                        new
                        {
                            Id_Detalle_Orden = 1,
                            Cantidad_Bebida = 1,
                            Cantidad_Platillo = 2,
                            Id_Bebida = 1,
                            Id_Orden = 1,
                            Id_Platillo = 1,
                            Precio = 100.00m
                        },
                        new
                        {
                            Id_Detalle_Orden = 2,
                            Cantidad_Bebida = 2,
                            Cantidad_Platillo = 1,
                            Id_Bebida = 2,
                            Id_Orden = 2,
                            Id_Platillo = 3,
                            Precio = 150.00m
                        },
                        new
                        {
                            Id_Detalle_Orden = 3,
                            Cantidad_Bebida = 3,
                            Cantidad_Platillo = 3,
                            Id_Bebida = 3,
                            Id_Orden = 3,
                            Id_Platillo = 2,
                            Precio = 200.00m
                        },
                        new
                        {
                            Id_Detalle_Orden = 4,
                            Cantidad_Bebida = 2,
                            Cantidad_Platillo = 1,
                            Id_Bebida = 4,
                            Id_Orden = 4,
                            Id_Platillo = 4,
                            Precio = 175.00m
                        },
                        new
                        {
                            Id_Detalle_Orden = 5,
                            Cantidad_Bebida = 1,
                            Cantidad_Platillo = 2,
                            Id_Bebida = 5,
                            Id_Orden = 5,
                            Id_Platillo = 5,
                            Precio = 125.00m
                        });
                });

            modelBuilder.Entity("backend.Models.Empleado", b =>
                {
                    b.Property<int>("Id_Empleado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id_Empleado"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("Contrasena")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Correo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id_Empleado");

                    b.ToTable("Empleado");

                    b.HasData(
                        new
                        {
                            Id_Empleado = 1,
                            Activo = true,
                            Contrasena = "root",
                            Correo = "juan.perez@gmail.com",
                            Nombre = "Juan Pérez"
                        },
                        new
                        {
                            Id_Empleado = 2,
                            Activo = true,
                            Contrasena = "root",
                            Correo = "maria.lopez@gmail.com",
                            Nombre = "María López"
                        },
                        new
                        {
                            Id_Empleado = 3,
                            Activo = true,
                            Contrasena = "root",
                            Correo = "carlos.garcia@gmail.com",
                            Nombre = "Carlos García"
                        },
                        new
                        {
                            Id_Empleado = 4,
                            Activo = true,
                            Contrasena = "root",
                            Correo = "laura.martinez@gmail.com",
                            Nombre = "Laura Martínez"
                        },
                        new
                        {
                            Id_Empleado = 5,
                            Activo = true,
                            Contrasena = "root",
                            Correo = "miguel.hernandez@gmail.com",
                            Nombre = "Miguel Hernández"
                        });
                });

            modelBuilder.Entity("backend.Models.Mesa", b =>
                {
                    b.Property<int>("Id_Mesa")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id_Mesa"));

                    b.Property<bool>("Activa")
                        .HasColumnType("bit");

                    b.Property<bool>("Disponible")
                        .HasColumnType("bit");

                    b.Property<string>("Numero_Mesa")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id_Mesa");

                    b.ToTable("Mesa");

                    b.HasData(
                        new
                        {
                            Id_Mesa = 1,
                            Activa = true,
                            Disponible = true,
                            Numero_Mesa = "1"
                        },
                        new
                        {
                            Id_Mesa = 2,
                            Activa = true,
                            Disponible = true,
                            Numero_Mesa = "2"
                        },
                        new
                        {
                            Id_Mesa = 3,
                            Activa = true,
                            Disponible = true,
                            Numero_Mesa = "5"
                        },
                        new
                        {
                            Id_Mesa = 4,
                            Activa = true,
                            Disponible = true,
                            Numero_Mesa = "1"
                        },
                        new
                        {
                            Id_Mesa = 5,
                            Activa = true,
                            Disponible = true,
                            Numero_Mesa = "8"
                        },
                        new
                        {
                            Id_Mesa = 6,
                            Activa = true,
                            Disponible = true,
                            Numero_Mesa = "3"
                        },
                        new
                        {
                            Id_Mesa = 7,
                            Activa = true,
                            Disponible = true,
                            Numero_Mesa = "6"
                        },
                        new
                        {
                            Id_Mesa = 8,
                            Activa = true,
                            Disponible = true,
                            Numero_Mesa = "9"
                        },
                        new
                        {
                            Id_Mesa = 9,
                            Activa = true,
                            Disponible = true,
                            Numero_Mesa = "4"
                        },
                        new
                        {
                            Id_Mesa = 10,
                            Activa = true,
                            Disponible = false,
                            Numero_Mesa = "7"
                        });
                });

            modelBuilder.Entity("backend.Models.Orden", b =>
                {
                    b.Property<int>("Id_Orden")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id_Orden"));

                    b.Property<bool>("Cancelado")
                        .HasColumnType("bit");

                    b.Property<int>("Cantidad_Personas")
                        .HasColumnType("int");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<TimeSpan>("Hora")
                        .HasColumnType("time");

                    b.Property<int>("Id_Chef")
                        .HasColumnType("int");

                    b.Property<int>("Id_Cliente")
                        .HasColumnType("int");

                    b.Property<int>("Id_Detalle_Orden")
                        .HasColumnType("int");

                    b.Property<int>("Id_Empleado")
                        .HasColumnType("int");

                    b.Property<int>("Id_Mesa")
                        .HasColumnType("int");

                    b.Property<int>("Numero_Orden")
                        .HasColumnType("int");

                    b.HasKey("Id_Orden");

                    b.HasIndex("Id_Chef");

                    b.HasIndex("Id_Cliente");

                    b.HasIndex("Id_Empleado");

                    b.HasIndex("Id_Mesa")
                        .IsUnique();

                    b.ToTable("Orden");

                    b.HasData(
                        new
                        {
                            Id_Orden = 1,
                            Cancelado = false,
                            Cantidad_Personas = 4,
                            Fecha = new DateTime(2024, 8, 21, 16, 48, 39, 950, DateTimeKind.Local).AddTicks(3105),
                            Hora = new TimeSpan(605199503115),
                            Id_Chef = 1,
                            Id_Cliente = 1,
                            Id_Detalle_Orden = 0,
                            Id_Empleado = 1,
                            Id_Mesa = 1,
                            Numero_Orden = 1
                        },
                        new
                        {
                            Id_Orden = 2,
                            Cancelado = false,
                            Cantidad_Personas = 2,
                            Fecha = new DateTime(2024, 8, 21, 16, 48, 39, 950, DateTimeKind.Local).AddTicks(3118),
                            Hora = new TimeSpan(605199503119),
                            Id_Chef = 2,
                            Id_Cliente = 2,
                            Id_Detalle_Orden = 0,
                            Id_Empleado = 2,
                            Id_Mesa = 2,
                            Numero_Orden = 2
                        },
                        new
                        {
                            Id_Orden = 3,
                            Cancelado = false,
                            Cantidad_Personas = 3,
                            Fecha = new DateTime(2024, 8, 21, 16, 48, 39, 950, DateTimeKind.Local).AddTicks(3121),
                            Hora = new TimeSpan(605199503121),
                            Id_Chef = 3,
                            Id_Cliente = 3,
                            Id_Detalle_Orden = 0,
                            Id_Empleado = 3,
                            Id_Mesa = 3,
                            Numero_Orden = 3
                        },
                        new
                        {
                            Id_Orden = 4,
                            Cancelado = false,
                            Cantidad_Personas = 5,
                            Fecha = new DateTime(2024, 8, 21, 16, 48, 39, 950, DateTimeKind.Local).AddTicks(3123),
                            Hora = new TimeSpan(605199503124),
                            Id_Chef = 4,
                            Id_Cliente = 4,
                            Id_Detalle_Orden = 0,
                            Id_Empleado = 4,
                            Id_Mesa = 4,
                            Numero_Orden = 4
                        },
                        new
                        {
                            Id_Orden = 5,
                            Cancelado = false,
                            Cantidad_Personas = 6,
                            Fecha = new DateTime(2024, 8, 21, 16, 48, 39, 950, DateTimeKind.Local).AddTicks(3125),
                            Hora = new TimeSpan(605199503126),
                            Id_Chef = 5,
                            Id_Cliente = 5,
                            Id_Detalle_Orden = 0,
                            Id_Empleado = 5,
                            Id_Mesa = 5,
                            Numero_Orden = 5
                        },
                        new
                        {
                            Id_Orden = 6,
                            Cancelado = false,
                            Cantidad_Personas = 2,
                            Fecha = new DateTime(2024, 8, 21, 16, 48, 39, 950, DateTimeKind.Local).AddTicks(3128),
                            Hora = new TimeSpan(605199503128),
                            Id_Chef = 2,
                            Id_Cliente = 6,
                            Id_Detalle_Orden = 0,
                            Id_Empleado = 1,
                            Id_Mesa = 6,
                            Numero_Orden = 6
                        },
                        new
                        {
                            Id_Orden = 7,
                            Cancelado = false,
                            Cantidad_Personas = 4,
                            Fecha = new DateTime(2024, 8, 21, 16, 48, 39, 950, DateTimeKind.Local).AddTicks(3130),
                            Hora = new TimeSpan(605199503131),
                            Id_Chef = 3,
                            Id_Cliente = 7,
                            Id_Detalle_Orden = 0,
                            Id_Empleado = 2,
                            Id_Mesa = 7,
                            Numero_Orden = 7
                        },
                        new
                        {
                            Id_Orden = 8,
                            Cancelado = false,
                            Cantidad_Personas = 3,
                            Fecha = new DateTime(2024, 8, 21, 16, 48, 39, 950, DateTimeKind.Local).AddTicks(3133),
                            Hora = new TimeSpan(605199503133),
                            Id_Chef = 4,
                            Id_Cliente = 8,
                            Id_Detalle_Orden = 0,
                            Id_Empleado = 3,
                            Id_Mesa = 8,
                            Numero_Orden = 8
                        },
                        new
                        {
                            Id_Orden = 9,
                            Cancelado = false,
                            Cantidad_Personas = 2,
                            Fecha = new DateTime(2024, 8, 21, 16, 48, 39, 950, DateTimeKind.Local).AddTicks(3135),
                            Hora = new TimeSpan(605199503135),
                            Id_Chef = 1,
                            Id_Cliente = 9,
                            Id_Detalle_Orden = 0,
                            Id_Empleado = 4,
                            Id_Mesa = 9,
                            Numero_Orden = 9
                        },
                        new
                        {
                            Id_Orden = 10,
                            Cancelado = false,
                            Cantidad_Personas = 4,
                            Fecha = new DateTime(2024, 8, 21, 16, 48, 39, 950, DateTimeKind.Local).AddTicks(3137),
                            Hora = new TimeSpan(605199503138),
                            Id_Chef = 5,
                            Id_Cliente = 10,
                            Id_Detalle_Orden = 0,
                            Id_Empleado = 5,
                            Id_Mesa = 10,
                            Numero_Orden = 10
                        });
                });

            modelBuilder.Entity("backend.Models.Platillo", b =>
                {
                    b.Property<int>("Id_Platillo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id_Platillo"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int?>("Id_Categoria")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Precio")
                        .HasPrecision(7, 2)
                        .HasColumnType("int");

                    b.HasKey("Id_Platillo");

                    b.HasIndex("Id_Categoria");

                    b.ToTable("Platillo");

                    b.HasData(
                        new
                        {
                            Id_Platillo = 1,
                            Descripcion = "Filete de res a la parrilla con acompañamiento de vegetales frescos.",
                            Id_Categoria = 2,
                            Nombre = "Filete de Res",
                            Precio = 15000
                        },
                        new
                        {
                            Id_Platillo = 2,
                            Descripcion = "Filete de salmón fresco horneado con hierbas y limón.",
                            Id_Categoria = 2,
                            Nombre = "Salmón al Horno",
                            Precio = 18000
                        },
                        new
                        {
                            Id_Platillo = 3,
                            Descripcion = "Pasta fettuccine en salsa cremosa de queso parmesano.",
                            Id_Categoria = 2,
                            Nombre = "Pasta Alfredo",
                            Precio = 12000
                        },
                        new
                        {
                            Id_Platillo = 4,
                            Descripcion = "Ensalada fresca con pollo a la parrilla y aderezo César.",
                            Id_Categoria = 6,
                            Nombre = "Ensalada César",
                            Precio = 9000
                        },
                        new
                        {
                            Id_Platillo = 5,
                            Descripcion = "Pizza tradicional con salsa de tomate, mozzarella y albahaca fresca.",
                            Id_Categoria = 2,
                            Nombre = "Pizza Margarita",
                            Precio = 14000
                        },
                        new
                        {
                            Id_Platillo = 6,
                            Descripcion = "Ceviche peruano con pescado, camarones y calamares en jugo de limón.",
                            Id_Categoria = 10,
                            Nombre = "Ceviche Mixto",
                            Precio = 16000
                        },
                        new
                        {
                            Id_Platillo = 7,
                            Descripcion = "Tacos mexicanos con carnitas de cerdo, cebolla y cilantro.",
                            Id_Categoria = 8,
                            Nombre = "Tacos de Carnitas",
                            Precio = 11000
                        },
                        new
                        {
                            Id_Platillo = 8,
                            Descripcion = "Paella española con arroz, mariscos, pollo y chorizo.",
                            Id_Categoria = 10,
                            Nombre = "Paella Valenciana",
                            Precio = 20000
                        },
                        new
                        {
                            Id_Platillo = 9,
                            Descripcion = "Variedad de sushi japonés: nigiri, sashimi y rollos especiales.",
                            Id_Categoria = 10,
                            Nombre = "Sushi Variado",
                            Precio = 22000
                        },
                        new
                        {
                            Id_Platillo = 10,
                            Descripcion = "Lasagna italiana con carne de res, salsa bolognesa y queso parmesano.",
                            Id_Categoria = 2,
                            Nombre = "Lasagna Bolognesa",
                            Precio = 13000
                        });
                });

            modelBuilder.Entity("DetalleOrdenBebida", b =>
                {
                    b.HasOne("backend.Models.Bebida", null)
                        .WithMany()
                        .HasForeignKey("Id_Bebida")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backend.Models.DetalleOrden", null)
                        .WithMany()
                        .HasForeignKey("Id_Detalle_Orden")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DetalleOrdenPlatillo", b =>
                {
                    b.HasOne("backend.Models.DetalleOrden", null)
                        .WithMany()
                        .HasForeignKey("Id_Detalle_Orden")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backend.Models.Platillo", null)
                        .WithMany()
                        .HasForeignKey("Id_Platillo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("backend.Models.Bebida", b =>
                {
                    b.HasOne("backend.Models.Categoria", "Categoria")
                        .WithMany("Bebidas")
                        .HasForeignKey("Id_Categoria");

                    b.Navigation("Categoria");
                });

            modelBuilder.Entity("backend.Models.Cuenta", b =>
                {
                    b.HasOne("backend.Models.Orden", "Orden")
                        .WithOne("Cuenta")
                        .HasForeignKey("backend.Models.Cuenta", "Id_Orden")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Orden");
                });

            modelBuilder.Entity("backend.Models.DetalleOrden", b =>
                {
                    b.HasOne("backend.Models.Orden", "Orden")
                        .WithOne("DetalleOrden")
                        .HasForeignKey("backend.Models.DetalleOrden", "Id_Orden")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_DetalleOrden_Orden");

                    b.Navigation("Orden");
                });

            modelBuilder.Entity("backend.Models.Orden", b =>
                {
                    b.HasOne("backend.Models.Chef", "Chef")
                        .WithMany("Ordenes")
                        .HasForeignKey("Id_Chef")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backend.Models.Cliente", "Cliente")
                        .WithMany("Ordenes")
                        .HasForeignKey("Id_Cliente")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backend.Models.Empleado", "Empleado")
                        .WithMany("Ordenes")
                        .HasForeignKey("Id_Empleado")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backend.Models.Mesa", "Mesa")
                        .WithOne("Orden")
                        .HasForeignKey("backend.Models.Orden", "Id_Mesa")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Chef");

                    b.Navigation("Cliente");

                    b.Navigation("Empleado");

                    b.Navigation("Mesa");
                });

            modelBuilder.Entity("backend.Models.Platillo", b =>
                {
                    b.HasOne("backend.Models.Categoria", "Categoria")
                        .WithMany("Platillos")
                        .HasForeignKey("Id_Categoria");

                    b.Navigation("Categoria");
                });

            modelBuilder.Entity("backend.Models.Categoria", b =>
                {
                    b.Navigation("Bebidas");

                    b.Navigation("Platillos");
                });

            modelBuilder.Entity("backend.Models.Chef", b =>
                {
                    b.Navigation("Ordenes");
                });

            modelBuilder.Entity("backend.Models.Cliente", b =>
                {
                    b.Navigation("Ordenes");
                });

            modelBuilder.Entity("backend.Models.Empleado", b =>
                {
                    b.Navigation("Ordenes");
                });

            modelBuilder.Entity("backend.Models.Mesa", b =>
                {
                    b.Navigation("Orden");
                });

            modelBuilder.Entity("backend.Models.Orden", b =>
                {
                    b.Navigation("Cuenta")
                        .IsRequired();

                    b.Navigation("DetalleOrden")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
